### PR TITLE
Tailwind 2.x upgrade

### PR DESCRIPTION
**Pull request by ryanmr**
this can be an ongoing pr

* upgrade tailwind to 2.x
* allow postcss to run through
* fixes some class name differences between versions

On the M1, I think only node 15 was available, so it pulled in npm@7 which caused there to be new package lock file. I did _not_ commit that with this branch. Instead @BrianMitchL can update the lock file from package.json.

### CODE REVIEW

**Comment by BrianMitchL** [comment]
A few notable inconsistencies I see between the current site and this:
- The text size classes adjust the line-height now, so we might want to explore something like the `leading-normal` class to give a little more height back to some headings maybe? If you don't like this idea, that's totally fine with me too 😜
- Sponsorship Opportunities: the emoji icons have the text-8xl class, which resets line-height to 1 now, causing there to be not enough space between the "Best Value" label and the emoji

Should we remove those custom fonts? They're really niche... Additionally, "New York" needs to be "New York Medium" or something too, and only works on macOS/iOS. I don't think we're even using any mono or serif text on the site either 😅

**Comment by ryanmr** [comment]
1. Yeah, tailwind 2 apply a line height now with font sizes. I'd have to stare at it more. I did notice it a couple places.
2. I'll see if the 7xl is good enough for the best value emoji and if not add 8xl back in.
3. The fonts could be fine, kind of a fun easter egg.

**Comment by ryanmr** [comment]
Today's updates:

- Fixed various issues in the sponsorship page
- Tweaked some issues with the footer
  - Footer had very close links in mobile mode, so added spacers
  - Footer had a border that was almost invisible from our initial rollout design, removed the border, it was not useful
- Adjusted leadings on pages with the signature slanted box header

**Comment by ryanmr** [comment]
Forgot about this:

- Changed "Learn more" on main page to "Speak at JSMN!"
  - Tried adding an icon into the button none looked good

**Comment by BrianMitchL** [comment]
Looks good, I committed a small tailwind config cleanup too. Do you want to let this sit for a little more, or merge it in?

**Comment by ryanmr** [comment]
I just ran a local build and then `serve`d it to check everything worked out. It looks good to me. Here's to hoping Tailwind 2 doesn't churn a ton!

**Comment by BrianMitchL** [comment]
Only time will tell!

**Pull request merged**
